version: '3.8'

services:
  db:
    image: postgres:14.13-alpine3.20
    container_name: postgres-db
    ports:
      - "5432:5432"
    env_file:
      - .env

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: